apiVersion: v1
kind: Service
metadata:
  name: messaging-backend-service
spec:
  type: LoadBalancer
  selector:
    app: messaging-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080